version: "3.9"

services:

  elasticsearch:
    image: elasticsearch:8.2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - http.host=elasticsearch
      - transport.host=localhost
      - network.host=0.0.0.0
      - cluster.name=es01
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
    volumes:
      - ./data/db:/usr/share/elasticsearch/data:rw

  kibana:
    container_name: kibana
    image: kibana:8.2.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

