version: "3.9"

services:

  ## Shards
  ## Shards:RS1
  mongo-rs1-1:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS1
    volumes:
      - ./data/rs-1/db-1:/data/db

  mongo-rs1-2:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS1
    volumes:
      - ./data/rs-1/db-2:/data/db

  mongo-rs1-3:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS1
    volumes:
      - ./data/rs-1/db-3:/data/db

  ## Shards:RS2
  mongo-rs2-1:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS2
    volumes:
      - ./data/rs-2/db-1:/data/db

  mongo-rs2-2:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS2
    volumes:
      - ./data/rs-2/db-2:/data/db

  mongo-rs2-3:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS2
    volumes:
      - ./data/rs-2/db-3:/data/db

  ## Shards:RS3
  mongo-rs3-1:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS3
    volumes:
      - ./data/rs-3/db-1:/data/db

  mongo-rs3-2:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS3
    volumes:
      - ./data/rs-3/db-2:/data/db

  mongo-rs3-3:
    image: mongo:4.4.14-focal
    command: mongod
      --shardsvr
      --replSet RS3
    volumes:
      - ./data/rs-3/db-3:/data/db

  ## Config Servers
  mongodb-cfg-1:
    image: mongo:4.4.14-focal
    command: mongod
      --configsvr
      --replSet RScfg
    volumes:
      - ./data/cfg/db-1:/data/configdb

  mongodb-cfg-2:
    image: mongo:4.4.14-focal
    command: mongod
      --configsvr
      --replSet RScfg
    volumes:
      - ./data/cfg/db-2:/data/configdb

  mongodb-cfg-3:
    image: mongo:4.4.14-focal
    command: mongod
      --configsvr
      --replSet RScfg
    volumes:
      - ./data/cfg/db-3:/data/configdb

  ## Routers
  mongos:
    image: mongo:4.4.14-focal
    command: mongos 
      --configdb RScfg/mongodb-cfg-1:27019,mongodb-cfg-2:27019,mongodb-cfg-3:27019
    depends_on:
      - mongodb-cfg-1
      - mongodb-cfg-2
      - mongodb-cfg-3

