version: "3.9"

services:

  couchbase1:
    image: couchbase/server:community-7.1.0-aarch64
    volumes:
      - ./data/node1:/opt/couchbase/var:rw

  couchbase2:
    image: couchbase/server:community-7.1.0-aarch64
    volumes:
      - ./data/node2:/opt/couchbase/var:rw

  couchbase3:
    image: couchbase/server:community-7.1.0-aarch64
    volumes:
      - ./data/node3:/opt/couchbase/var:rw
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210